package com.gcu.data.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Entity class that maps to the "workout" table in the database.
 * <p>
 * This class represents a persistent workout record stored in the system and
 * is used by Spring Data to read/write workout information to the database.
 * Each workout is associated with a specific user through their email address.
 */
@Table("workout")
public class WorkoutEntity {

    /**
     * Unique identifier for the workout record (primary key).
     * Automatically generated by the database.
     */
    @Id
    private Long id;

    /**
     * Email address of the user who logged the workout.
     * Used to associate workout records with a specific account.
     */
    private String email;

    /**
     * Type of workout (e.g., Running, Cycling, Strength Training).
     */
    private String type;

    /**
     * Duration of the workout in minutes.
     */
    private int duration;

    /**
     * Number of calories burned during the workout session.
     * Maps to column "calories_burned" in the database.
     */
    @Column("calories_burned")
    private int caloriesBurned;

    /**
     * Default constructor required by Spring Data and ORM mapping frameworks.
     */
    public WorkoutEntity() {}

    /**
     * Constructs a new WorkoutEntity with all fields initialized.
     *
     * @param id              unique identifier of the workout record
     * @param type            type of workout performed
     * @param caloriesBurned  calories burned during the workout
     * @param duration        length of the workout in minutes
     * @param email           email address of the user logging the workout
     */
    public WorkoutEntity(Long id, String type, int caloriesBurned, int duration, String email) {
        this.id = id;
        this.type = type;
        this.caloriesBurned = caloriesBurned;
        this.duration = duration;
        this.email = email;
    }

    /**
     * Gets the unique workout identifier.
     *
     * @return workout ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique workout identifier.
     *
     * @param id workout ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the email of the user associated with the workout.
     *
     * @return user email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the user email associated with the workout.
     *
     * @param email user email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the type of workout.
     *
     * @return workout type
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the type of workout.
     *
     * @param type workout type
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Gets the workout duration in minutes.
     *
     * @return workout duration
     */
    public int getDuration() {
        return duration;
    }

    /**
     * Sets the workout duration in minutes.
     *
     * @param duration workout duration
     */
    public void setDuration(int duration) {
        this.duration = duration;
    }

    /**
     * Gets the total calories burned during the workout.
     *
     * @return calories burned
     */
    public int getCaloriesBurned() {
        return caloriesBurned;
    }

    /**
     * Sets the total calories burned during the workout.
     *
     * @param caloriesBurned calories burned
     */
    public void setCaloriesBurned(int caloriesBurned) {
        this.caloriesBurned = caloriesBurned;
    }
}
